### ISSUE TITLE
No option for viewing document in Only Office

### ISSUE THREAD

**Issue by nadirlc** [exo-addons/onlyoffice#10]
Hi,

I installed exo-onlyoffice addon v1.1.1. We are using Exo Platform v4.4. The problem is that the options for viewing the document in Only Office do not show. For example the "Edit in Only Office" button does not show.

The platform.log file shows the following error:

2017-11-10 09:31:02,140 | ERROR | ContainerBase.removeChild: destroy:  [org.apache.catalina.core.ContainerBase<main>] 
org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_destroy]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/onlyoffice]] in state [STARTED]
	at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:395) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:287) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:1030) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1230) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:292) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:1030) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1230) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:292) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardService.destroyInternal(StandardService.java:594) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:292) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardServer.destroyInternal(StandardServer.java:846) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:292) [catalina.jar:7.0.72]
	at org.apache.catalina.startup.Catalina.stop(Catalina.java:767) [catalina.jar:7.0.72]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:728) [catalina.jar:7.0.72]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:294) [bootstrap.jar:7.0.72]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:428) [bootstrap.jar:7.0.72]

**Comment by pnedonosko** [comment]
@nadirlc is this problem still actual?

**Comment by nadirlc** [comment]
Well we stopped using the Exo Office.

**Comment by pnedonosko** [comment]
Ok, I see. Thank you for responding. I consider this issue as not actual.
