### ISSUE TITLE
Addon not work with exo platform 4.4.0 release 

### ISSUE THREAD

**Issue by laigor** [exo-addons/onlyoffice#2]
ERROR | An error occurs while processing 'Javascript in gatein-resources.xml' from the context 'onlyoffice' [o.e.w.a.j.JavascriptConfigDeployer<Catalina-startStop-1>] 
java.lang.IllegalStateException: Duplicate ResourceId : SHARED/jqueryPnotify, later resource definition will be ignored
	at org.gatein.portal.controller.resource.script.ScriptGraph.addResource(ScriptGraph.java:223) ~[exo.portal.component.web.resources-4.4.0-PLF.jar:4.4.0-PLF]
	at org.exoplatform.web.application.javascript.JavascriptTask.execute(JavascriptTask.java:49) ~[exo.portal.component.web.resources-4.4.0-PLF.jar:4.4.0-PLF]
	at org.exoplatform.web.application.javascript.JavascriptConfigParser.processConfigResource(JavascriptConfigParser.java:133) ~[exo.portal.component.web.resources-4.4.0-PLF.jar:4.4.0-PLF]
	at org.exoplatform.web.application.javascript.JavascriptConfigDeployer.register(JavascriptConfigDeployer.java:94) ~[exo.portal.component.web.resources-4.4.0-PLF.jar:4.4.0-PLF]
	at org.exoplatform.web.application.javascript.JavascriptConfigDeployer.access$000(JavascriptConfigDeployer.java:42) ~[exo.portal.component.web.resources-4.4.0-PLF.jar:4.4.0-PLF]
	at org.exoplatform.web.application.javascript.JavascriptConfigDeployer$1.execute(JavascriptConfigDeployer.java:66) ~[exo.portal.component.web.resources-4.4.0-PLF.jar:4.4.0-PLF]
	at org.exoplatform.container.RootContainer.executeInitTasks(RootContainer.java:1317) [exo.kernel.container-2.6.0.jar:2.6.0]
	at org.exoplatform.container.RootContainer.createPortalContainer(RootContainer.java:780) [exo.kernel.container-2.6.0.jar:2.6.0]
	at org.exoplatform.container.RootContainer.createPortalContainers(RootContainer.java:356) [exo.kernel.container-2.6.0.jar:2.6.0]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator$1.run(PortalContainersCreator.java:52) [plf-tomcat-pc-creator-listener-4.4.0.jar:4.4.0]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator$1.run(PortalContainersCreator.java:50) [plf-tomcat-pc-creator-listener-4.4.0.jar:4.4.0]
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedAction(SecurityHelper.java:291) [exo.kernel.commons-2.6.0.jar:2.6.0]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator.createPortalContainers(PortalContainersCreator.java:50) [plf-tomcat-pc-creator-listener-4.4.0.jar:4.4.0]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator.lifecycleEvent(PortalContainersCreator.java:39) [plf-tomcat-pc-creator-listener-4.4.0.jar:4.4.0]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:388) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:333) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1136) [catalina.jar:7.0.72]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:819) [catalina.jar:7.0.72]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571) [catalina.jar:7.0.72]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561) [catalina.jar:7.0.72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by pnedonosko** [comment]
Thank you for reporting this. Platform 4.4 has changed several things internally, thus need more general picture of the problem - can you provide a full server log for this/such start, may be there is something prior the error logged? 
You are also welcome to ask your questions in [eXo Tribe](https://community.exoplatform.com/portal), join the Onlyoffice space and ask in the [forum](https://community.exoplatform.com/portal/g/:spaces:onlyoffice/onlyoffice/forum).

**Comment by Marc-pastel** [comment]
There is a discussion here : https://community.exoplatform.com/portal/intranet/forum/forum/forum245d501b0a2106c66cc87b1bc52d47b1
But still not possible to use this addon with exo 4.4

**Comment by pnedonosko** [comment]
We just released a version 1.1.0 for Platform 4.4. It is available in the Add-ons catalog. Use it with the latest Onlyoffice version.
